version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  # examples
  - package-ecosystem: pip
    directory: /examples
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /examples
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  # docs_src
  - package-ecosystem: pip
    directory: /docs_src
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /docs_src
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
